library(fmsb)
library(ggpubr)
library(data.table)
library(dplyr)
library(ggplot2)

# k1 <- fread(file="Output_1k-n_10000bp_unbalanced.csv", header=T)
# # k1 <- t(k1)
# k1 <- as.data.frame(k1)
# k1$mean <- rowMeans(k1)
# k1$sd <- apply(k1, 1, sd)
# metrics <- rownames(k1)
# k1 <- cbind(metrics,k1)
# k1 <- subset(k1, select = c(metrics,mean,sd))
# type <- c(rep("{1,k-1}-mer" , nrow(k1)))
# k1 <- cbind(k1,type)
# frag <- c(rep("10.000 bp" , nrow(k1)))
# k1 <- cbind(k1,frag)
# k <- c(rep("2" , nrow(k1)))
# k1 <- cbind(k1,k)
#  
# k2 <- fread(file="Output_2k-n_10000bp_unbalanced.csv", header=T)
# k2 <- t(k2)
# k2 <- as.data.frame(k2)
# k2$mean <- rowMeans(k2)
# k2$sd <- apply(k2, 1, sd)
# metrics <- rownames(k2)
# k2 <- cbind(metrics,k2)
# k2 <- subset(k2, select = c(metrics,mean,sd))
# type <- c(rep("{2,k-2}-mer" , nrow(k2)))
# k2 <- cbind(k2,type)
# frag <- c(rep("10.000 bp" , nrow(k2)))
# k2 <- cbind(k2,frag)
# k <- c(rep("2" , nrow(k2)))
# k2 <- cbind(k2,k)
# kvalues <- rbind(k1,k2)
# 
# k3 <- fread(file="Output_3k-n_10000bp_unbalanced.csv", header=T)
# k3 <- t(k3)
# k3 <- as.data.frame(k3)
# k3$mean <- rowMeans(k3)
# k3$sd <- apply(k3, 1, sd)
# metrics <- rownames(k3)
# k3 <- cbind(metrics,k3)
# k3 <- subset(k3, select = c(metrics,mean,sd))
# type <- c(rep("{3,k-3}-mer" , nrow(k3)))
# k3 <- cbind(k3,type)
# frag <- c(rep("10.000 bp" , nrow(k3)))
# k3 <- cbind(k3,frag)
# k <- c(rep("2" , nrow(k3)))
# k3 <- cbind(k3,k)
# kvalues <- rbind(kvalues,k3)
# 
# k4 <- fread(file="Output_kmer_10000bp_unbalanced.csv", header=T)
# k4 <- t(k4)
# k4 <- as.data.frame(k4)
# k4$mean <- rowMeans(k4)
# k4$sd <- apply(k4, 1, sd)
# metrics <- rownames(k4)
# k4 <- cbind(metrics,k4)
# k4 <- subset(k4, select = c(metrics,mean,sd))
# type <- c(rep("{0,k}-mer" , nrow(k4)))
# k4 <- cbind(k4,type)
# frag <- c(rep("10.000 bp" , nrow(k4)))
# k4 <- cbind(k4,frag)
# k <- c(rep("2" , nrow(k4)))
# k4 <- cbind(k4,k)
# kvalues <- rbind(kvalues,k4)
# 
# k1 <- fread(file="Output_1k-n_1000bp_unbalanced.csv", header=T)
# k1 <- t(k1)
# k1 <- as.data.frame(k1)
# k1$mean <- rowMeans(k1)
# k1$sd <- apply(k1, 1, sd)
# metrics <- rownames(k1)
# k1 <- cbind(metrics,k1)
# k1 <- subset(k1, select = c(metrics,mean,sd))
# type <- c(rep("{1,k-1}-mer" , nrow(k1)))
# k1 <- cbind(k1,type)
# frag <- c(rep("1.000 bp" , nrow(k1)))
# k1 <- cbind(k1,frag)
# k <- c(rep("2" , nrow(k1)))
# k1 <- cbind(k1,k)
# kvalues <- rbind(kvalues,k1)
# 
# k2 <- fread(file="Output_2k-n_1000bp_unbalanced.csv", header=T)
# k2 <- t(k2)
# k2 <- as.data.frame(k2)
# k2$mean <- rowMeans(k2)
# k2$sd <- apply(k2, 1, sd)
# metrics <- rownames(k2)
# k2 <- cbind(metrics,k2)
# k2 <- subset(k2, select = c(metrics,mean,sd))
# type <- c(rep("{2,k-2}-mer" , nrow(k2)))
# k2 <- cbind(k2,type)
# frag <- c(rep("1.000 bp" , nrow(k2)))
# k2 <- cbind(k2,frag)
# k <- c(rep("2" , nrow(k2)))
# k2 <- cbind(k2,k)
# kvalues <- rbind(kvalues,k2)
# 
# k3 <- fread(file="Output_3k-n_1000bp_unbalanced.csv", header=T)
# k3 <- t(k3)
# k3 <- as.data.frame(k3)
# k3$mean <- rowMeans(k3)
# k3$sd <- apply(k3, 1, sd)
# metrics <- rownames(k3)
# k3 <- cbind(metrics,k3)
# k3 <- subset(k3, select = c(metrics,mean,sd))
# type <- c(rep("{3,k-3}-mer" , nrow(k3)))
# k3 <- cbind(k3,type)
# frag <- c(rep("1.000 bp" , nrow(k3)))
# k3 <- cbind(k3,frag)
# k <- c(rep("2" , nrow(k3)))
# k3 <- cbind(k3,k)
# kvalues <- rbind(kvalues,k3)
# 
# k4 <- fread(file="Output_kmer_1000bp_unbalanced.csv", header=T)
# k4 <- t(k4)
# k4 <- as.data.frame(k4)
# k4$mean <- rowMeans(k4)
# k4$sd <- apply(k4, 1, sd)
# metrics <- rownames(k4)
# k4 <- cbind(metrics,k4)
# k4 <- subset(k4, select = c(metrics,mean,sd))
# type <- c(rep("{0,k}-mer" , nrow(k4)))
# k4 <- cbind(k4,type)
# frag <- c(rep("1.000 bp" , nrow(k4)))
# k4 <- cbind(k4,frag)
# k <- c(rep("2" , nrow(k4)))
# k4 <- cbind(k4,k)
# kvalues <- rbind(kvalues,k4)
# 
# k1 <- fread(file="Output_1k-n_300bp_unbalanced.csv", header=T)
# k1 <- t(k1)
# k1 <- as.data.frame(k1)
# k1$mean <- rowMeans(k1)
# k1$sd <- apply(k1, 1, sd)
# metrics <- rownames(k1)
# k1 <- cbind(metrics,k1)
# k1 <- subset(k1, select = c(metrics,mean,sd))
# type <- c(rep("{1,k-1}-mer" , nrow(k1)))
# k1 <- cbind(k1,type)
# frag <- c(rep("300 bp" , nrow(k1)))
# k1 <- cbind(k1,frag)
# k <- c(rep("2" , nrow(k1)))
# k1 <- cbind(k1,k)
# kvalues <- rbind(kvalues,k1)
# 
# k2 <- fread(file="Output_2k-n_300bp_unbalanced.csv", header=T)
# k2 <- t(k2)
# k2 <- as.data.frame(k2)
# k2$mean <- rowMeans(k2)
# k2$sd <- apply(k2, 1, sd)
# metrics <- rownames(k2)
# k2 <- cbind(metrics,k2)
# k2 <- subset(k2, select = c(metrics,mean,sd))
# type <- c(rep("{2,k-2}-mer" , nrow(k2)))
# k2 <- cbind(k2,type)
# frag <- c(rep("300 bp" , nrow(k2)))
# k2 <- cbind(k2,frag)
# k <- c(rep("2" , nrow(k2)))
# k2 <- cbind(k2,k)
# kvalues <- rbind(kvalues,k2)
# 
# k3 <- fread(file="Output_3k-n_300bp_unbalanced.csv", header=T)
# k3 <- t(k3)
# k3 <- as.data.frame(k3)
# k3$mean <- rowMeans(k3)
# k3$sd <- apply(k3, 1, sd)
# metrics <- rownames(k3)
# k3 <- cbind(metrics,k3)
# k3 <- subset(k3, select = c(metrics,mean,sd))
# type <- c(rep("{3,k-3}-mer" , nrow(k3)))
# k3 <- cbind(k3,type)
# frag <- c(rep("300 bp" , nrow(k3)))
# k3 <- cbind(k3,frag)
# k <- c(rep("2" , nrow(k3)))
# k3 <- cbind(k3,k)
# kvalues <- rbind(kvalues,k3)
# 
# k4 <- fread(file="Output_kmer_300bp_unbalanced.csv", header=T)
# k4 <- t(k4)
# k4 <- as.data.frame(k4)
# k4$mean <- rowMeans(k4)
# k4$sd <- apply(k4, 1, sd)
# metrics <- rownames(k4)
# k4 <- cbind(metrics,k4)
# k4 <- subset(k4, select = c(metrics,mean,sd))
# type <- c(rep("{0,k}-mer" , nrow(k4)))
# k4 <- cbind(k4,type)
# frag <- c(rep("300 bp" , nrow(k4)))
# k4 <- cbind(k4,frag)
# k <- c(rep("2" , nrow(k4)))
# k4 <- cbind(k4,k)
# kvalues <- rbind(kvalues,k4)
# 
# k1 <- fread(file="Output_1k-n_3000bp_unbalanced.csv", header=T)
# k1 <- t(k1)
# k1 <- as.data.frame(k1)
# k1$mean <- rowMeans(k1)
# k1$sd <- apply(k1, 1, sd)
# metrics <- rownames(k1)
# k1 <- cbind(metrics,k1)
# k1 <- subset(k1, select = c(metrics,mean,sd))
# type <- c(rep("{1,k-1}-mer" , nrow(k1)))
# k1 <- cbind(k1,type)
# frag <- c(rep("3.000 bp" , nrow(k1)))
# k1 <- cbind(k1,frag)
# k <- c(rep("2" , nrow(k1)))
# k1 <- cbind(k1,k)
# kvalues <- rbind(kvalues,k1)
# 
# k2 <- fread(file="Output_2k-n_3000bp_unbalanced.csv", header=T)
# k2 <- t(k2)
# k2 <- as.data.frame(k2)
# k2$mean <- rowMeans(k2)
# k2$sd <- apply(k2, 1, sd)
# metrics <- rownames(k2)
# k2 <- cbind(metrics,k2)
# k2 <- subset(k2, select = c(metrics,mean,sd))
# type <- c(rep("{2,k-2}-mer" , nrow(k2)))
# k2 <- cbind(k2,type)
# frag <- c(rep("3.000 bp" , nrow(k2)))
# k2 <- cbind(k2,frag)
# k <- c(rep("2" , nrow(k2)))
# k2 <- cbind(k2,k)
# kvalues <- rbind(kvalues,k2)
# 
# k3 <- fread(file="Output_3k-n_3000bp_unbalanced.csv", header=T)
# k3 <- t(k3)
# k3 <- as.data.frame(k3)
# k3$mean <- rowMeans(k3)
# k3$sd <- apply(k3, 1, sd)
# metrics <- rownames(k3)
# k3 <- cbind(metrics,k3)
# k3 <- subset(k3, select = c(metrics,mean,sd))
# type <- c(rep("{3,k-3}-mer" , nrow(k3)))
# k3 <- cbind(k3,type)
# frag <- c(rep("3.000 bp" , nrow(k3)))
# k3 <- cbind(k3,frag)
# k <- c(rep("2" , nrow(k3)))
# k3 <- cbind(k3,k)
# kvalues <- rbind(kvalues,k3)
# 
# k4 <- fread(file="Output_kmer_3000bp_unbalanced.csv", header=T)
# k4 <- t(k4)
# k4 <- as.data.frame(k4)
# k4$mean <- rowMeans(k4)
# k4$sd <- apply(k4, 1, sd)
# metrics <- rownames(k4)
# k4 <- cbind(metrics,k4)
# k4 <- subset(k4, select = c(metrics,mean,sd))
# type <- c(rep("{0,k}-mer" , nrow(k4)))
# k4 <- cbind(k4,type)
# frag <- c(rep("3.000 bp" , nrow(k4)))
# k4 <- cbind(k4,frag)
# k <- c(rep("2" , nrow(k4)))
# k4 <- cbind(k4,k)
# kvalues <- rbind(kvalues,k4)
# 
# k1 <- fread(file="Output_1k-n_5000bp_unbalanced.csv", header=T)
# k1 <- t(k1)
# k1 <- as.data.frame(k1)
# k1$mean <- rowMeans(k1)
# k1$sd <- apply(k1, 1, sd)
# metrics <- rownames(k1)
# k1 <- cbind(metrics,k1)
# k1 <- subset(k1, select = c(metrics,mean,sd))
# type <- c(rep("{1,k-1}-mer" , nrow(k1)))
# k1 <- cbind(k1,type)
# frag <- c(rep("5.000 bp" , nrow(k1)))
# k1 <- cbind(k1,frag)
# k <- c(rep("2" , nrow(k1)))
# k1 <- cbind(k1,k)
# kvalues <- rbind(kvalues,k1)
# 
# k2 <- fread(file="Output_2k-n_5000bp_unbalanced.csv", header=T)
# k2 <- t(k2)
# k2 <- as.data.frame(k2)
# k2$mean <- rowMeans(k2)
# k2$sd <- apply(k2, 1, sd)
# metrics <- rownames(k2)
# k2 <- cbind(metrics,k2)
# k2 <- subset(k2, select = c(metrics,mean,sd))
# type <- c(rep("{2,k-2}-mer" , nrow(k2)))
# k2 <- cbind(k2,type)
# frag <- c(rep("5.000 bp" , nrow(k2)))
# k2 <- cbind(k2,frag)
# k <- c(rep("2" , nrow(k2)))
# k2 <- cbind(k2,k)
# kvalues <- rbind(kvalues,k2)
# 
# k3 <- fread(file="Output_3k-n_5000bp_unbalanced.csv", header=T)
# k3 <- t(k3)
# k3 <- as.data.frame(k3)
# k3$mean <- rowMeans(k3)
# k3$sd <- apply(k3, 1, sd)
# metrics <- rownames(k3)
# k3 <- cbind(metrics,k3)
# k3 <- subset(k3, select = c(metrics,mean,sd))
# type <- c(rep("{3,k-3}-mer" , nrow(k3)))
# k3 <- cbind(k3,type)
# frag <- c(rep("5.000 bp" , nrow(k3)))
# k3 <- cbind(k3,frag)
# k <- c(rep("2" , nrow(k3)))
# k3 <- cbind(k3,k)
# kvalues <- rbind(kvalues,k3)
# 
# k4 <- fread(file="Output_kmer_5000bp_unbalanced.csv", header=T)
# k4 <- t(k4)
# k4 <- as.data.frame(k4)
# k4$mean <- rowMeans(k4)
# k4$sd <- apply(k4, 1, sd)
# metrics <- rownames(k4)
# k4 <- cbind(metrics,k4)
# k4 <- subset(k4, select = c(metrics,mean,sd))
# type <- c(rep("{0,k}-mer" , nrow(k4)))
# k4 <- cbind(k4,type)
# frag <- c(rep("5.000 bp" , nrow(k4)))
# k4 <- cbind(k4,frag)
# k <- c(rep("2" , nrow(k4)))
# k4 <- cbind(k4,k)
# kvalues <- rbind(kvalues,k4)
# 
# write.csv(kvalues, file="meanMetrics_VClassifier.csv", row.names=F)

df <- fread(file="meanMetrics_VClassifier_AUC.csv",header=T)
df$frag = factor(df$frag, levels=c('300 bp','1.000 bp','3.000 bp','5.000 bp','10.000 bp'))

p2 <- ggplot(df, aes(x=frag, y=mean, group=type, color=type)) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, position=position_dodge(0.05)) + 
  geom_line() + geom_point() + theme_linedraw() + 
  theme(strip.text.y = element_text(angle = 0))
p2
p3 <- p2 + 
  labs(x=NULL, y = "mean AUC", fill = NULL) + 
  theme(axis.text = element_text(colour = "black", size=12,family='Arial')) 
p3
p5 <- p3 + 
  theme(axis.title = element_text(family = "Arial", size = 12), axis.text = element_text(family = "Arial"), axis.text.x = element_text(family = "Arial"), legend.text = element_text(size = 12, family = "Arial"))+
  scale_color_manual(values=c("{0,k}-mer"="#CC3300","{1,k-1}-mer"="#6BAED6","{2,k-2}-mer"="#4292C6","{3,k-3}-mer"="#2171B5"))
p5
#p <- p5 + 
#  scale_y_continuous(limits = c(0, 260), 
#                     breaks = seq(0,260, by = 100))

p1 <- p5 + 
  theme_linedraw() + 
  theme(strip.text = element_text(colour = 'black')) + 
  theme(strip.background =element_rect(fill="white")) + theme(legend.position="top") 
p1

library(ggpubr)
teste <- ggpar(p1, font.x = c(10,"black"),
               font.y = c(10,"black"),
               font.tickslab = c(10,"black"),
               legend = "top")
teste

png("AUCS_VClassifier_paper_menor.png", 
    width = 2000, 
    height = 550, 
    res = 400)
teste
dev.off()

###spiderplot

human<-c(0.96,0.95,0.96,0.95,0.95,0.95)
mn1 <- c(0.979,0.9824,0.973,0.98,0.979,0.979)
mn2 <-c(0.973,0.9936,0.971,0.97,0.97,0.97)
mn3 <-c(0.985,0.98829,0.970,0.98,0.98,0.98)

values <- rbind(human,mn1)
values <- rbind(values,mn2)
values <- rbind(values,mn3)
colnames(values) <- c("Accuracy","Sensibility","Specificity","Precision","Recall","F1")
values <- as.data.frame(values)

max_min <- data.frame(Accuracy = c(1, 0.90), Sensibility = c(1, 0.90), Specificity = c(1, 0.90),Precision = c(1, 0.90), Recall = c(1, 0.90), F1 = c(1, 0.90))
rownames(max_min) <- c("Max", "Min")
# Bind the variable ranges to the data
values <- rbind(max_min, values)

colors_border <- c("#CC3300","#9ECAE1","#4292C6","#084594")

png("Spider_VClassifier_paper.png", 
    width = 2000, 
    height =1500, 
    res = 400)
radarchart(values, axistype=6 , pcol=colors_border, plwd=2, plty=1, cglcol="black", cglty=5, axislabcol="black", cglwd=0.5, vlcex=1)
dev.off()
